/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';
import '@stencil/router';

import {
  RouterHistory,
} from '@stencil/router';
import {
  EventEmitter,
} from '@stencil/core';
import {
  Listing,
  ListingCard,
  Map,
  Profile,
  Thumbnails,
} from './global/interfaces';
import {
  SearchOptionInterface,
  SearchProvider,
} from './global/interfaces-app';

declare global {

  namespace StencilComponents {
    interface AmRating {
      /**
       * Determines if half ratings are allowed
       */
      'allowHalfRatings': boolean;
      /**
       * The color to fill the rating with when it's outwith the max
       */
      'colorOff': string;
      /**
       * The color to fill the rating with when it's within the max
       */
      'colorOn': string;
      /**
       * The color to fill the rating with when it's outwith the max
       */
      'colorOutline': string;
      /**
       * The direction of the shading. Valid settings are 'ltr' (left to right) and 'ttb' (top to bottom)
       */
      'direction': string;
      /**
       * Determines if the user can set a rating
       */
      'interactive': boolean;
      /**
       * The maximum rating possible
       */
      'maxRating': number;
      /**
       * The minimum rating possible
       */
      'minRating': number;
      /**
       * The rating
       */
      'rating': number;
      /**
       * The rating identifier
       */
      'reference': string;
      /**
       * This is a star!
       */
      'svgPoints': string;
      /**
       * The view box for the SVG
       */
      'svgViewBox': string;
    }
  }

  interface HTMLAmRatingElement extends StencilComponents.AmRating, HTMLStencilElement {}

  var HTMLAmRatingElement: {
    prototype: HTMLAmRatingElement;
    new (): HTMLAmRatingElement;
  };
  interface HTMLElementTagNameMap {
    'am-rating': HTMLAmRatingElement;
  }
  interface ElementTagNameMap {
    'am-rating': HTMLAmRatingElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'am-rating': JSXElements.AmRatingAttributes;
    }
  }
  namespace JSXElements {
    export interface AmRatingAttributes extends HTMLAttributes {
      /**
       * Determines if half ratings are allowed
       */
      'allowHalfRatings'?: boolean;
      /**
       * The color to fill the rating with when it's outwith the max
       */
      'colorOff'?: string;
      /**
       * The color to fill the rating with when it's within the max
       */
      'colorOn'?: string;
      /**
       * The color to fill the rating with when it's outwith the max
       */
      'colorOutline'?: string;
      /**
       * The direction of the shading. Valid settings are 'ltr' (left to right) and 'ttb' (top to bottom)
       */
      'direction'?: string;
      /**
       * Determines if the user can set a rating
       */
      'interactive'?: boolean;
      /**
       * The maximum rating possible
       */
      'maxRating'?: number;
      /**
       * The minimum rating possible
       */
      'minRating'?: number;
      /**
       * Event fired when the rating is updated by user input
       */
      'onRatingUpdated'?: (event: CustomEvent) => void;
      /**
       * The rating
       */
      'rating'?: number;
      /**
       * The rating identifier
       */
      'reference'?: string;
      /**
       * This is a star!
       */
      'svgPoints'?: string;
      /**
       * The view box for the SVG
       */
      'svgViewBox'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface BazaarDogStencil {

    }
  }

  interface HTMLBazaarDogStencilElement extends StencilComponents.BazaarDogStencil, HTMLStencilElement {}

  var HTMLBazaarDogStencilElement: {
    prototype: HTMLBazaarDogStencilElement;
    new (): HTMLBazaarDogStencilElement;
  };
  interface HTMLElementTagNameMap {
    'bazaar-dog-stencil': HTMLBazaarDogStencilElement;
  }
  interface ElementTagNameMap {
    'bazaar-dog-stencil': HTMLBazaarDogStencilElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bazaar-dog-stencil': JSXElements.BazaarDogStencilAttributes;
    }
  }
  namespace JSXElements {
    export interface BazaarDogStencilAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface FavoritesPage {

    }
  }

  interface HTMLFavoritesPageElement extends StencilComponents.FavoritesPage, HTMLStencilElement {}

  var HTMLFavoritesPageElement: {
    prototype: HTMLFavoritesPageElement;
    new (): HTMLFavoritesPageElement;
  };
  interface HTMLElementTagNameMap {
    'favorites-page': HTMLFavoritesPageElement;
  }
  interface ElementTagNameMap {
    'favorites-page': HTMLFavoritesPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'favorites-page': JSXElements.FavoritesPageAttributes;
    }
  }
  namespace JSXElements {
    export interface FavoritesPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface FeedList {
      'posts': any;
    }
  }

  interface HTMLFeedListElement extends StencilComponents.FeedList, HTMLStencilElement {}

  var HTMLFeedListElement: {
    prototype: HTMLFeedListElement;
    new (): HTMLFeedListElement;
  };
  interface HTMLElementTagNameMap {
    'feed-list': HTMLFeedListElement;
  }
  interface ElementTagNameMap {
    'feed-list': HTMLFeedListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'feed-list': JSXElements.FeedListAttributes;
    }
  }
  namespace JSXElements {
    export interface FeedListAttributes extends HTMLAttributes {
      'posts'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface FeedPageModal {

    }
  }

  interface HTMLFeedPageModalElement extends StencilComponents.FeedPageModal, HTMLStencilElement {}

  var HTMLFeedPageModalElement: {
    prototype: HTMLFeedPageModalElement;
    new (): HTMLFeedPageModalElement;
  };
  interface HTMLElementTagNameMap {
    'feed-page-modal': HTMLFeedPageModalElement;
  }
  interface ElementTagNameMap {
    'feed-page-modal': HTMLFeedPageModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'feed-page-modal': JSXElements.FeedPageModalAttributes;
    }
  }
  namespace JSXElements {
    export interface FeedPageModalAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface FeedPage {

    }
  }

  interface HTMLFeedPageElement extends StencilComponents.FeedPage, HTMLStencilElement {}

  var HTMLFeedPageElement: {
    prototype: HTMLFeedPageElement;
    new (): HTMLFeedPageElement;
  };
  interface HTMLElementTagNameMap {
    'feed-page': HTMLFeedPageElement;
  }
  interface ElementTagNameMap {
    'feed-page': HTMLFeedPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'feed-page': JSXElements.FeedPageAttributes;
    }
  }
  namespace JSXElements {
    export interface FeedPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface HomePage {
      'history': RouterHistory;
    }
  }

  interface HTMLHomePageElement extends StencilComponents.HomePage, HTMLStencilElement {}

  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };
  interface HTMLElementTagNameMap {
    'home-page': HTMLHomePageElement;
  }
  interface ElementTagNameMap {
    'home-page': HTMLHomePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'home-page': JSXElements.HomePageAttributes;
    }
  }
  namespace JSXElements {
    export interface HomePageAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface LazyImg {
      'alt': string;
      'src': string;
    }
  }

  interface HTMLLazyImgElement extends StencilComponents.LazyImg, HTMLStencilElement {}

  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ListingDetail {
      'peerId': string;
      'slug': string;
    }
  }

  interface HTMLListingDetailElement extends StencilComponents.ListingDetail, HTMLStencilElement {}

  var HTMLListingDetailElement: {
    prototype: HTMLListingDetailElement;
    new (): HTMLListingDetailElement;
  };
  interface HTMLElementTagNameMap {
    'listing-detail': HTMLListingDetailElement;
  }
  interface ElementTagNameMap {
    'listing-detail': HTMLListingDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listing-detail': JSXElements.ListingDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface ListingDetailAttributes extends HTMLAttributes {
      'peerId'?: string;
      'slug'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ListingItem {
      'fave': Boolean;
      'listing': ListingCard;
    }
  }

  interface HTMLListingItemElement extends StencilComponents.ListingItem, HTMLStencilElement {}

  var HTMLListingItemElement: {
    prototype: HTMLListingItemElement;
    new (): HTMLListingItemElement;
  };
  interface HTMLElementTagNameMap {
    'listing-item': HTMLListingItemElement;
  }
  interface ElementTagNameMap {
    'listing-item': HTMLListingItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listing-item': JSXElements.ListingItemAttributes;
    }
  }
  namespace JSXElements {
    export interface ListingItemAttributes extends HTMLAttributes {
      'fave'?: Boolean;
      'listing'?: ListingCard;
      'onListingDeleted'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ListingList {
      'fave': Boolean;
      'listings': Array<ListingCard>;
    }
  }

  interface HTMLListingListElement extends StencilComponents.ListingList, HTMLStencilElement {}

  var HTMLListingListElement: {
    prototype: HTMLListingListElement;
    new (): HTMLListingListElement;
  };
  interface HTMLElementTagNameMap {
    'listing-list': HTMLListingListElement;
  }
  interface ElementTagNameMap {
    'listing-list': HTMLListingListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listing-list': JSXElements.ListingListAttributes;
    }
  }
  namespace JSXElements {
    export interface ListingListAttributes extends HTMLAttributes {
      'fave'?: Boolean;
      'listings'?: Array<ListingCard>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ListingPage {

    }
  }

  interface HTMLListingPageElement extends StencilComponents.ListingPage, HTMLStencilElement {}

  var HTMLListingPageElement: {
    prototype: HTMLListingPageElement;
    new (): HTMLListingPageElement;
  };
  interface HTMLElementTagNameMap {
    'listing-page': HTMLListingPageElement;
  }
  interface ElementTagNameMap {
    'listing-page': HTMLListingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listing-page': JSXElements.ListingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ListingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ListingSlideshow {
      'images': Array<Thumbnails>;
    }
  }

  interface HTMLListingSlideshowElement extends StencilComponents.ListingSlideshow, HTMLStencilElement {}

  var HTMLListingSlideshowElement: {
    prototype: HTMLListingSlideshowElement;
    new (): HTMLListingSlideshowElement;
  };
  interface HTMLElementTagNameMap {
    'listing-slideshow': HTMLListingSlideshowElement;
  }
  interface ElementTagNameMap {
    'listing-slideshow': HTMLListingSlideshowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listing-slideshow': JSXElements.ListingSlideshowAttributes;
    }
  }
  namespace JSXElements {
    export interface ListingSlideshowAttributes extends HTMLAttributes {
      'images'?: Array<Thumbnails>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MainPage {

    }
  }

  interface HTMLMainPageElement extends StencilComponents.MainPage, HTMLStencilElement {}

  var HTMLMainPageElement: {
    prototype: HTMLMainPageElement;
    new (): HTMLMainPageElement;
  };
  interface HTMLElementTagNameMap {
    'main-page': HTMLMainPageElement;
  }
  interface ElementTagNameMap {
    'main-page': HTMLMainPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'main-page': JSXElements.MainPageAttributes;
    }
  }
  namespace JSXElements {
    export interface MainPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface PopoverPage {

    }
  }

  interface HTMLPopoverPageElement extends StencilComponents.PopoverPage, HTMLStencilElement {}

  var HTMLPopoverPageElement: {
    prototype: HTMLPopoverPageElement;
    new (): HTMLPopoverPageElement;
  };
  interface HTMLElementTagNameMap {
    'popover-page': HTMLPopoverPageElement;
  }
  interface ElementTagNameMap {
    'popover-page': HTMLPopoverPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'popover-page': JSXElements.PopoverPageAttributes;
    }
  }
  namespace JSXElements {
    export interface PopoverPageAttributes extends HTMLAttributes {
      'onClosePopover'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface PostDetail {
      'post': any;
    }
  }

  interface HTMLPostDetailElement extends StencilComponents.PostDetail, HTMLStencilElement {}

  var HTMLPostDetailElement: {
    prototype: HTMLPostDetailElement;
    new (): HTMLPostDetailElement;
  };
  interface HTMLElementTagNameMap {
    'post-detail': HTMLPostDetailElement;
  }
  interface ElementTagNameMap {
    'post-detail': HTMLPostDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'post-detail': JSXElements.PostDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface PostDetailAttributes extends HTMLAttributes {
      'post'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface PostImg {
      'alt': string;
      'src': string;
    }
  }

  interface HTMLPostImgElement extends StencilComponents.PostImg, HTMLStencilElement {}

  var HTMLPostImgElement: {
    prototype: HTMLPostImgElement;
    new (): HTMLPostImgElement;
  };
  interface HTMLElementTagNameMap {
    'post-img': HTMLPostImgElement;
  }
  interface ElementTagNameMap {
    'post-img': HTMLPostImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'post-img': JSXElements.PostImgAttributes;
    }
  }
  namespace JSXElements {
    export interface PostImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface PostItem {
      'post': any;
    }
  }

  interface HTMLPostItemElement extends StencilComponents.PostItem, HTMLStencilElement {}

  var HTMLPostItemElement: {
    prototype: HTMLPostItemElement;
    new (): HTMLPostItemElement;
  };
  interface HTMLElementTagNameMap {
    'post-item': HTMLPostItemElement;
  }
  interface ElementTagNameMap {
    'post-item': HTMLPostItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'post-item': JSXElements.PostItemAttributes;
    }
  }
  namespace JSXElements {
    export interface PostItemAttributes extends HTMLAttributes {
      'post'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProfileDetail {
      'peerId': string;
    }
  }

  interface HTMLProfileDetailElement extends StencilComponents.ProfileDetail, HTMLStencilElement {}

  var HTMLProfileDetailElement: {
    prototype: HTMLProfileDetailElement;
    new (): HTMLProfileDetailElement;
  };
  interface HTMLElementTagNameMap {
    'profile-detail': HTMLProfileDetailElement;
  }
  interface ElementTagNameMap {
    'profile-detail': HTMLProfileDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'profile-detail': JSXElements.ProfileDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface ProfileDetailAttributes extends HTMLAttributes {
      'peerId'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProfileHeader {

    }
  }

  interface HTMLProfileHeaderElement extends StencilComponents.ProfileHeader, HTMLStencilElement {}

  var HTMLProfileHeaderElement: {
    prototype: HTMLProfileHeaderElement;
    new (): HTMLProfileHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'profile-header': HTMLProfileHeaderElement;
  }
  interface ElementTagNameMap {
    'profile-header': HTMLProfileHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'profile-header': JSXElements.ProfileHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface ProfileHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProfileList {
      'profiles': Array<Profile>;
    }
  }

  interface HTMLProfileListElement extends StencilComponents.ProfileList, HTMLStencilElement {}

  var HTMLProfileListElement: {
    prototype: HTMLProfileListElement;
    new (): HTMLProfileListElement;
  };
  interface HTMLElementTagNameMap {
    'profile-list': HTMLProfileListElement;
  }
  interface ElementTagNameMap {
    'profile-list': HTMLProfileListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'profile-list': JSXElements.ProfileListAttributes;
    }
  }
  namespace JSXElements {
    export interface ProfileListAttributes extends HTMLAttributes {
      'profiles'?: Array<Profile>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProfilePage {

    }
  }

  interface HTMLProfilePageElement extends StencilComponents.ProfilePage, HTMLStencilElement {}

  var HTMLProfilePageElement: {
    prototype: HTMLProfilePageElement;
    new (): HTMLProfilePageElement;
  };
  interface HTMLElementTagNameMap {
    'profile-page': HTMLProfilePageElement;
  }
  interface ElementTagNameMap {
    'profile-page': HTMLProfilePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'profile-page': JSXElements.ProfilePageAttributes;
    }
  }
  namespace JSXElements {
    export interface ProfilePageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface RatingItem {
      'ratingHash': string;
    }
  }

  interface HTMLRatingItemElement extends StencilComponents.RatingItem, HTMLStencilElement {}

  var HTMLRatingItemElement: {
    prototype: HTMLRatingItemElement;
    new (): HTMLRatingItemElement;
  };
  interface HTMLElementTagNameMap {
    'rating-item': HTMLRatingItemElement;
  }
  interface ElementTagNameMap {
    'rating-item': HTMLRatingItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rating-item': JSXElements.RatingItemAttributes;
    }
  }
  namespace JSXElements {
    export interface RatingItemAttributes extends HTMLAttributes {
      'onListingDeleted'?: (event: CustomEvent) => void;
      'ratingHash'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface RatingList {
      'ratingHashes': Array<string>;
    }
  }

  interface HTMLRatingListElement extends StencilComponents.RatingList, HTMLStencilElement {}

  var HTMLRatingListElement: {
    prototype: HTMLRatingListElement;
    new (): HTMLRatingListElement;
  };
  interface HTMLElementTagNameMap {
    'rating-list': HTMLRatingListElement;
  }
  interface ElementTagNameMap {
    'rating-list': HTMLRatingListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rating-list': JSXElements.RatingListAttributes;
    }
  }
  namespace JSXElements {
    export interface RatingListAttributes extends HTMLAttributes {
      'ratingHashes'?: Array<string>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SearchMenu {
      'options': Map<SearchOptionInterface>;
    }
  }

  interface HTMLSearchMenuElement extends StencilComponents.SearchMenu, HTMLStencilElement {}

  var HTMLSearchMenuElement: {
    prototype: HTMLSearchMenuElement;
    new (): HTMLSearchMenuElement;
  };
  interface HTMLElementTagNameMap {
    'search-menu': HTMLSearchMenuElement;
  }
  interface ElementTagNameMap {
    'search-menu': HTMLSearchMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'search-menu': JSXElements.SearchMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface SearchMenuAttributes extends HTMLAttributes {
      'onLeftSidebarClick'?: (event: CustomEvent) => void;
      'options'?: Map<SearchOptionInterface>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SearchOption {
      'init': any;
      'onSearchParamCheckboxActivated': (event: any) => void;
      'onSearchParamDropdownActivated': (event: any) => void;
      'onSearchParamRadioActivated': (event: any) => void;
      'option': SearchOptionInterface;
      'param': string;
    }
  }

  interface HTMLSearchOptionElement extends StencilComponents.SearchOption, HTMLStencilElement {}

  var HTMLSearchOptionElement: {
    prototype: HTMLSearchOptionElement;
    new (): HTMLSearchOptionElement;
  };
  interface HTMLElementTagNameMap {
    'search-option': HTMLSearchOptionElement;
  }
  interface ElementTagNameMap {
    'search-option': HTMLSearchOptionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'search-option': JSXElements.SearchOptionAttributes;
    }
  }
  namespace JSXElements {
    export interface SearchOptionAttributes extends HTMLAttributes {
      'init'?: any;
      'onOnSearchParamChange'?: (event: CustomEvent<{ param: string; value: any }>) => void;
      'option'?: SearchOptionInterface;
      'param'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SearchProvider {
      'searchProviders': Array<SearchProvider>;
      'storedSearchProvider': SearchProvider;
    }
  }

  interface HTMLSearchProviderElement extends StencilComponents.SearchProvider, HTMLStencilElement {}

  var HTMLSearchProviderElement: {
    prototype: HTMLSearchProviderElement;
    new (): HTMLSearchProviderElement;
  };
  interface HTMLElementTagNameMap {
    'search-provider': HTMLSearchProviderElement;
  }
  interface ElementTagNameMap {
    'search-provider': HTMLSearchProviderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'search-provider': JSXElements.SearchProviderAttributes;
    }
  }
  namespace JSXElements {
    export interface SearchProviderAttributes extends HTMLAttributes {
      'onBackgroundToggle'?: (event: CustomEvent) => void;
      'onOnSearchProviderChange'?: (event: CustomEvent) => void;
      'searchProviders'?: Array<SearchProvider>;
      'storedSearchProvider'?: SearchProvider;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SettingsPage {

    }
  }

  interface HTMLSettingsPageElement extends StencilComponents.SettingsPage, HTMLStencilElement {}

  var HTMLSettingsPageElement: {
    prototype: HTMLSettingsPageElement;
    new (): HTMLSettingsPageElement;
  };
  interface HTMLElementTagNameMap {
    'settings-page': HTMLSettingsPageElement;
  }
  interface ElementTagNameMap {
    'settings-page': HTMLSettingsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'settings-page': JSXElements.SettingsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface SettingsPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ShareButton {
      'listing': any;
    }
  }

  interface HTMLShareButtonElement extends StencilComponents.ShareButton, HTMLStencilElement {}

  var HTMLShareButtonElement: {
    prototype: HTMLShareButtonElement;
    new (): HTMLShareButtonElement;
  };
  interface HTMLElementTagNameMap {
    'share-button': HTMLShareButtonElement;
  }
  interface ElementTagNameMap {
    'share-button': HTMLShareButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'share-button': JSXElements.ShareButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface ShareButtonAttributes extends HTMLAttributes {
      'listing'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SplashPage {

    }
  }

  interface HTMLSplashPageElement extends StencilComponents.SplashPage, HTMLStencilElement {}

  var HTMLSplashPageElement: {
    prototype: HTMLSplashPageElement;
    new (): HTMLSplashPageElement;
  };
  interface HTMLElementTagNameMap {
    'splash-page': HTMLSplashPageElement;
  }
  interface ElementTagNameMap {
    'splash-page': HTMLSplashPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'splash-page': JSXElements.SplashPageAttributes;
    }
  }
  namespace JSXElements {
    export interface SplashPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StoreItem {
      'fave': Boolean;
      'listing': Listing;
      'peerID': string;
    }
  }

  interface HTMLStoreItemElement extends StencilComponents.StoreItem, HTMLStencilElement {}

  var HTMLStoreItemElement: {
    prototype: HTMLStoreItemElement;
    new (): HTMLStoreItemElement;
  };
  interface HTMLElementTagNameMap {
    'store-item': HTMLStoreItemElement;
  }
  interface ElementTagNameMap {
    'store-item': HTMLStoreItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'store-item': JSXElements.StoreItemAttributes;
    }
  }
  namespace JSXElements {
    export interface StoreItemAttributes extends HTMLAttributes {
      'fave'?: Boolean;
      'listing'?: Listing;
      'onListingDeleted'?: (event: CustomEvent) => void;
      'peerID'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StoreList {
      'fave': Boolean;
      'listings': Array<Listing>;
      'peerID': string;
    }
  }

  interface HTMLStoreListElement extends StencilComponents.StoreList, HTMLStencilElement {}

  var HTMLStoreListElement: {
    prototype: HTMLStoreListElement;
    new (): HTMLStoreListElement;
  };
  interface HTMLElementTagNameMap {
    'store-list': HTMLStoreListElement;
  }
  interface ElementTagNameMap {
    'store-list': HTMLStoreListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'store-list': JSXElements.StoreListAttributes;
    }
  }
  namespace JSXElements {
    export interface StoreListAttributes extends HTMLAttributes {
      'fave'?: Boolean;
      'listings'?: Array<Listing>;
      'peerID'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface TabsPage {

    }
  }

  interface HTMLTabsPageElement extends StencilComponents.TabsPage, HTMLStencilElement {}

  var HTMLTabsPageElement: {
    prototype: HTMLTabsPageElement;
    new (): HTMLTabsPageElement;
  };
  interface HTMLElementTagNameMap {
    'tabs-page': HTMLTabsPageElement;
  }
  interface ElementTagNameMap {
    'tabs-page': HTMLTabsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tabs-page': JSXElements.TabsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface TabsPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface UserProfile {
      'userName': any;
    }
  }

  interface HTMLUserProfileElement extends StencilComponents.UserProfile, HTMLStencilElement {}

  var HTMLUserProfileElement: {
    prototype: HTMLUserProfileElement;
    new (): HTMLUserProfileElement;
  };
  interface HTMLElementTagNameMap {
    'user-profile': HTMLUserProfileElement;
  }
  interface ElementTagNameMap {
    'user-profile': HTMLUserProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'user-profile': JSXElements.UserProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface UserProfileAttributes extends HTMLAttributes {
      'userName'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface UsersList {
      'users': any[];
    }
  }

  interface HTMLUsersListElement extends StencilComponents.UsersList, HTMLStencilElement {}

  var HTMLUsersListElement: {
    prototype: HTMLUsersListElement;
    new (): HTMLUsersListElement;
  };
  interface HTMLElementTagNameMap {
    'users-list': HTMLUsersListElement;
  }
  interface ElementTagNameMap {
    'users-list': HTMLUsersListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'users-list': JSXElements.UsersListAttributes;
    }
  }
  namespace JSXElements {
    export interface UsersListAttributes extends HTMLAttributes {
      'users'?: any[];
    }
  }
}


declare global {

  namespace StencilComponents {
    interface UsersPage {

    }
  }

  interface HTMLUsersPageElement extends StencilComponents.UsersPage, HTMLStencilElement {}

  var HTMLUsersPageElement: {
    prototype: HTMLUsersPageElement;
    new (): HTMLUsersPageElement;
  };
  interface HTMLElementTagNameMap {
    'users-page': HTMLUsersPageElement;
  }
  interface ElementTagNameMap {
    'users-page': HTMLUsersPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'users-page': JSXElements.UsersPageAttributes;
    }
  }
  namespace JSXElements {
    export interface UsersPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface XuiCheckbox {
      'checked': boolean;
      'label': string;
      'radio': boolean;
      'slider': boolean;
      'toggle': boolean;
    }
  }

  interface HTMLXuiCheckboxElement extends StencilComponents.XuiCheckbox, HTMLStencilElement {}

  var HTMLXuiCheckboxElement: {
    prototype: HTMLXuiCheckboxElement;
    new (): HTMLXuiCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'xui-checkbox': HTMLXuiCheckboxElement;
  }
  interface ElementTagNameMap {
    'xui-checkbox': HTMLXuiCheckboxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'xui-checkbox': JSXElements.XuiCheckboxAttributes;
    }
  }
  namespace JSXElements {
    export interface XuiCheckboxAttributes extends HTMLAttributes {
      'checked'?: boolean;
      'label'?: string;
      'radio'?: boolean;
      'slider'?: boolean;
      'toggle'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface XuiDropdownItem {
      'active': boolean;
      'icon': string;
      'text': string;
      'value': any;
    }
  }

  interface HTMLXuiDropdownItemElement extends StencilComponents.XuiDropdownItem, HTMLStencilElement {}

  var HTMLXuiDropdownItemElement: {
    prototype: HTMLXuiDropdownItemElement;
    new (): HTMLXuiDropdownItemElement;
  };
  interface HTMLElementTagNameMap {
    'xui-dropdown-item': HTMLXuiDropdownItemElement;
  }
  interface ElementTagNameMap {
    'xui-dropdown-item': HTMLXuiDropdownItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'xui-dropdown-item': JSXElements.XuiDropdownItemAttributes;
    }
  }
  namespace JSXElements {
    export interface XuiDropdownItemAttributes extends HTMLAttributes {
      'active'?: boolean;
      'icon'?: string;
      'text'?: string;
      'value'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface XuiDropdown {
      'icon': string;
      'name': string;
      'openOnFocus': boolean;
      'selection': boolean;
      'text': string;
      'value': any;
    }
  }

  interface HTMLXuiDropdownElement extends StencilComponents.XuiDropdown, HTMLStencilElement {}

  var HTMLXuiDropdownElement: {
    prototype: HTMLXuiDropdownElement;
    new (): HTMLXuiDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'xui-dropdown': HTMLXuiDropdownElement;
  }
  interface ElementTagNameMap {
    'xui-dropdown': HTMLXuiDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'xui-dropdown': JSXElements.XuiDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface XuiDropdownAttributes extends HTMLAttributes {
      'icon'?: string;
      'name'?: string;
      'onInput'?: (event: CustomEvent) => void;
      'openOnFocus'?: boolean;
      'selection'?: boolean;
      'text'?: string;
      'value'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface XuiSegment {
      'active': boolean;
      'attach': any;
      'dataTab': string;
      'tab': boolean;
    }
  }

  interface HTMLXuiSegmentElement extends StencilComponents.XuiSegment, HTMLStencilElement {}

  var HTMLXuiSegmentElement: {
    prototype: HTMLXuiSegmentElement;
    new (): HTMLXuiSegmentElement;
  };
  interface HTMLElementTagNameMap {
    'xui-segment': HTMLXuiSegmentElement;
  }
  interface ElementTagNameMap {
    'xui-segment': HTMLXuiSegmentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'xui-segment': JSXElements.XuiSegmentAttributes;
    }
  }
  namespace JSXElements {
    export interface XuiSegmentAttributes extends HTMLAttributes {
      'active'?: boolean;
      'attach'?: any;
      'dataTab'?: string;
      'tab'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
